//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by pcProGUI.rc
//
#define IDC_ADD_GROUP                   3
#define IDC_ADD_SLOT                    3
#define ID_REMOVE                       4
#define IDC_ADD_OP                      4
#define IDC_DELETE_SLOT                 4
#define IDC_DELETE_VAR_GROUP            4
#define ID_REMOVE_ALL                   5
#define IDC_DELETE_GROUP                5
#define IDC_DELETE_OP                   6
#define IDC_SET_OP                      8
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_PCPROTYPE                   129
#define IDR_PCPROTYPE1                  130
#define IDI_NO_CHECK                    131
#define IDI_CHECK                       132
#define IDR_MENU_CFG                    134
#define IDD_CONSOLE                     135
#define IDR_MENU_ILG                    135
#define IDR_CONSOLETOOLBAR              136
#define IDD_PROPERTIES                  136
#define IDR_MENU_HTG                    136
#define IDD_PROP_INSTR                  136
#define IDI_OLDMAIN                     137
#define IDI_PLAIN                       138
#define IDD_PROP_UNIT                   138
#define IDD_PROP_CONN                   139
#define IDR_EXPRESSION                  140
#define IDD_PROP_PORT                   140
#define IDD_PROP_STOR                   141
#define IDR_SIMULATOR                   142
#define IDD_PROP_BASE                   142
#define IDR_MENU_SIM                    143
#define IDD_PROP_FILE                   143
#define IDD_PROP_BBLOCK                 144
#define IDD_PROP_HTG_SIMPLE             145
#define IDD_PROP_HTG_IF                 146
#define IDD_PROP_HTG_LOOP               147
#define IDD_PROP_HTG_COMPOUND           148
#define IDD_PROP_COMP_UNIT              149
#define IDD_PROP_LATCH                  150
#define IDD_PROP_PIPELINESTAGE          151
#define IDD_DATAPATHS                   152
#define IDD_STAT_SIM                    153
#define IDD_DIALOG1                     154
#define IDD_STAT_COMP_UNIT              155
#define IDD_STAT_CONN                   156
#define IDD_STAT_LATCH                  157
#define IDD_STAT_PORT                   158
#define IDD_STAT_STOR                   159
#define IDD_STAT_UNIT                   160
#define IDD_ADD_STAT                    161
#define IDD_IS_OP_GROUPS                162
#define IDD_IS_INSTR_DESCR              163
#define IDI_UP                          169
#define IDI_DOWN                        170
#define IDD_IS_OP_MAPPINGS              171
#define IDD_IS_VAR_GROUP                172
#define IDI_DELETE                      173
#define IDD_PROP_BUS                    173
#define IDI_ADD                         174
#define IDD_PROP_ROUTINE                174
#define IDD_IS_OP_MAPPINGS1             175
#define IDI_ADD_OP                      176
#define IDI_ADD_GROUP                   177
#define IDI_DEL_GROUP                   178
#define IDI_DEL_OP                      179
#define IDI_CFILE                       180
#define IDR_COMPILER                    180
#define IDI_FUNC                        181
#define IDI_CFILE_CHECK                 182
#define IDR_GRAPHS                      182
#define IDI_FUNC_CHECK                  183
#define IDC_STATUS                      1000
#define IDC_TEMP                        1000
#define IDC_EDIT1                       1001
#define IDC_SELECTION                   1001
#define IDC_MAPPING_TEXT                1001
#define IDC_BEHAVIOR                    1001
#define IDC_DATATYPE                    1001
#define IDC_MNEMONIC                    1001
#define IDC_OP_LIST                     1002
#define IDC_MEM_SIZE                    1002
#define IDC_HEIGHT                      1002
#define IDC_COMPONENTS                  1002
#define IDC_LIST1                       1003
#define IDC_ADDRESS2                    1003
#define IDC_ADDR_RANGE_FROM             1003
#define IDC_OPCODES                     1003
#define IDC_DATAPATHS                   1003
#define IDC_STATS                       1003
#define IDC_STAT_LIST                   1003
#define IDC_SLOT_LIST                   1003
#define IDC_VAR_GROUPS                  1003
#define IDC_OP_TREE                     1003
#define IDC_NAME                        1004
#define IDC_ADDR_RANGE_TO               1004
#define IDC_DISP_LIST                   1004
#define IDC_NAME2                       1005
#define IDC_APPLY                       1006
#define IDC_UNDO                        1007
#define IDC_INSTR_LIST                  1008
#define IDC_LINE                        1008
#define IDC_TIMING                      1008
#define IDC_CLASS_NAME                  1008
#define IDC_REMOVE_STAT                 1008
#define IDC_PERCOLATE                   1008
#define IDC_MOVE_OP                     1008
#define IDC_REGFILE                     1009
#define IDC_ADD_STAT                    1009
#define IDC_MOVE_CJ                     1009
#define IDC_INSTRIN                     1009
#define IDC_RAM                         1010
#define IDC_UNIFY                       1010
#define IDC_INSTROUT                    1010
#define IDC_SRAM                        1010
#define IDC_CACHE                       1011
#define IDC_MIGRATE                     1011
#define IDC_ICACHE                      1011
#define IDC_ACCESS_TIME                 1012
#define IDC_CUSTOM_PROP                 1013
#define IDC_ASSOCIATIVITY               1014
#define IDC_WIDTH_L                     1015
#define IDC_LINE_L                      1016
#define IDC_ACCESS_TIME_L               1017
#define IDC_ASSOCIATIVITY_L             1018
#define IDC_ADDR_RANGE_TO_L             1019
#define IDC_ADDR_RANGE_FROM_L           1020
#define IDC_WIDTH                       1021
#define IDC_ADDR_RANGE_L                1022
#define IDC_CAPACITY                    1023
#define IDC_DCACHE                      1023
#define IDC_OPCODES_ALL                 1024
#define IDC_DRAM                        1024
#define IDC_OPCODES_SELECTED            1025
#define IDC_OPCODES_SELECTED_BACK       1026
#define IDC_SUBUNITS                    1027
#define IDC_CLASS_NAME2                 1027
#define IDC_CLASS_NAME3                 1028
#define IDC_PORT_TYPE_READ              1028
#define IDC_PORT_TYPE_WRITE             1029
#define IDC_PORT_TYPE_READWRITE         1030
#define IDC_LATCH_TYPE_INPUT            1036
#define IDC_LATCH_TYPE_OUTPUT           1037
#define IDC_LATCH_TYPE_OTHER            1038
#define IDC_TYPE                        1041
#define IDC_UP                          1042
#define IDC_UNIT                        1043
#define IDC_DOWN                        1044
#define IDC_ADD_VAR_GROUP               1047
#define IDC_BITWIDTH                    1048
#define IDC_WORDLEN                     1049
#define IDC_CHECK1                      1051
#define IDC_OPERAND_TYPE_11             1052
#define IDC_OPERAND_11                  1053
#define IDC_CHECK2                      1054
#define IDC_OPERAND_TYPE_21             1055
#define IDC_OPERAND_21                  1056
#define IDC_CHECK3                      1057
#define IDC_OPERAND_TYPE_31             1058
#define IDC_OPERAND_31                  1059
#define IDC_PRINT_CFG                   1059
#define IDC_TREE1                       1060
#define IDC_PRINT_HTG                   1060
#define IDC_AFTER_TBZ                   1061
#define IDC_DO_TBZ                      1062
#define IDC_DO_TBZ_PIPE                 1063
#define IDC_OPERAND_TYPE_12             1064
#define IDC_DO_MUT                      1064
#define IDC_OPERAND_12                  1065
#define IDC_SIM_HTG                     1065
#define IDC_OPERAND_TYPE_13             1066
#define IDC_PRINT_IL                    1066
#define IDC_OPERAND_13                  1067
#define IDC_SIM_NOSSA                   1067
#define IDC_OPERAND_TYPE_14             1068
#define IDC_SIM_SSA                     1068
#define IDC_OPERAND_14                  1069
#define IDC_SIM_ISEL                    1069
#define IDC_OPERAND_TYPE_22             1070
#define IDC_SIM_TBZ                     1070
#define IDC_OPERAND_22                  1071
#define IDC_DO_ISEL                     1071
#define IDC_OPERAND_TYPE_23             1072
#define IDC_PRINT_MC                    1072
#define IDC_RICHTEXTCTRL1               1072
#define IDC_OPERAND_23                  1073
#define IDC_DO_UNROLL                   1073
#define IDC_OPERAND_TYPE_24             1074
#define IDC_OPERAND_24                  1075
#define IDC_OPERAND_TYPE_32             1076
#define IDC_OPERAND_32                  1077
#define IDC_OPERAND_TYPE_33             1078
#define IDC_OPERAND_33                  1079
#define IDC_OPERAND_TYPE_34             1080
#define IDC_AAMSREDIT1                  1080
#define IDC_OPERAND_34                  1081
#define IDC_EDIT2                       1082
#define IDC_EDIT3                       1083
#define IDC_MAPPING_TEXT1               1083
#define IDC_MEM_SIZE_L                  1093
#define IDC_MNEMONIC_L                  1094
#define ID_VIEW_CONSOLE                 32771
#define ID_PROJECT_ADD                  32772
#define ID_PROJECT_REMOVE               32773
#define ID_CONSOLE_CLEAR                32775
#define ID_CONSOLE_COPY                 32776
#define ID_PROJECT_COMPILE              32776
#define ID_PROJECT_BUILD                32778
#define ID_GRAPHS_CONTROLFLOWGRAPH      32781
#define ID_GRAPHS_CFG                   32782
#define ID_GRAPHS_HIERARCHICALTASKGRAPH 32783
#define ID_GRAPHS_HTG                   32784
#define ID_GRAPHS_INSTRUCTIONLISTGRAPH  32786
#define ID_GRAPHS_ILG                   32787
#define ID_PBB_EXPAND                   32788
#define ID_PBB_UDDU                     32789
#define ID_PBB_SHOWPROPERTIES           32790
#define ID_ADD_STORAGE                  32797
#define ID_SIM_STOP                     32803
#define ID_SIM_RESET                    32804
#define ID_SIM_STEP                     32805
#define ID_SIM_RUN                      32806
#define ID_ADD_UNIT                     32807
#define ID_ADD_CONNECTION               32809
#define ID_COMPONENTS_ADDPORT           32810
#define ID_SIM_NEW                      32811
#define ID_ADD_PORT                     32815
#define ID_DEFAULT                      32816
#define ID_BREAK                        32817
#define ID_SIM_CONNECTION_TYPE_1        32820
#define ID_SIM_STORAGE_TYPE_1           32821
#define ID_SIM_UNIT_TYPE_1              32822
#define ID_SIM_UNIT_TYPE_2              32823
#define ID_                             32824
#define ID_SIM_PORT_TYPE_1              32825
#define ID_SIM_PORT_TYPE_2              32826
#define ID_SIM_CONNECTION_TYPE_2        32828
#define ID_SIM_STORAGE_TYPE_2           32830
#define ID_ADD_COMP_UNIT                32832
#define ID_SIM_COMP_UNIT_TYPE_1         32833
#define ID_SIM_COMP_UNIT_TYPE_2         32834
#define ID_FILE_LOAD_EXPR_INSTR_DESC    32835
#define ID_FILE_SAVE_EXPR_DESCR         32836
#define ID_FILE_LOAD_GRAPHICAL_MACHINE_DESCRIPTION 32837
#define ID_FILE_SAVE_GRAPHICAL_MACHINE_DESCRIPTION 32838
#define ID_ADD_LATCH                    32839
#define ID_SIM_LATCH_TYPE_2             32840
#define ID_SIM_LATCH_TYPE_1             32841
#define ID_ADD_PIPELINESTAGE            32842
#define ID_DATAPATH                     32844
#define ID_ADD_DATAPATH                 32845
#define ID_EDIT_DATAPATHS               32846
#define ID_RESIZE                       32847
#define ID_TEMP_SWITCHTOSTATISTICS      32848
#define ID_TEMP_UNLOCKSIM               32849
#define ID_INSTRUCTIONSET_SETVARGROUPS  32854
#define ID_INSTRUCTIONSET_SETOPGROUPS   32855
#define ID_INSTRUCTIONSET_SETOPMAPPINGS 32856
#define ID_INSTRUCTIONSET_SETINSTRUCTIONDESCRIPTION 32857
#define ID_LOAD_IS_DESCR                32858
#define ID_SAVE_IS_DESCR                32860
#define ID_FILE_SAVE_GRAPHICAL_MACHINE_DESCRIPTION_AS 32861
#define ID_FILE_SAVE_EXPR_DESCR_AS      32862
#define ID_SAVE_IS_DESCR_AS             32863
#define ID_ADD_BUS                      32864
#define ID_FILE_SAVE_EXPR_DESCR_AS_C    32866
#define ID_COMPILE_STEPCOMPILE_SSA      32867
#define ID_COMPILE_STEPCOMPILE_BUILDHTG 32868
#define ID_COMPILE_STEPCOMPILE_UDDUANALYSIS 32869
#define ID_COMPILE_STEPCOMPILE_TRAILBLAZING 32870
#define ID_COMPILE_STEPCOMPILE_INITIALIZECOMPILER 32871
#define ID_PBB_PRINT                    32872
#define ID_IFCONVERT                    32873
#define ID_COMPILE_STEPCOMPILE_PRINTROUTINE 32881
#define ID_PBB_UD                       32882
#define ID_PBB_DU                       32883
#define ID_PERCOLATE                    32884
#define ID_REFRESH_GRAPH                32886
#define ID_PBB_SETSTART                 32887
#define ID_PBB_SETSTOP                  32888
#define ID_IFCONVERT_MARK               32889
#define ID_MARK_BLOCKS                  32895
#define ID_PBB_SETPERC                  32896
#define ID_PBB_RESETPERC                32897
#define ID_DELETE                       32898
#define ID_INSTRUCTIONSET_SETOPERANDMAPPING 32899

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32900
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
